export const STATIC_ROUTES = [
  {
    isDeleted: false,
    deletedAt: null,
    deleteUser: null,
    createdAt: '2025-11-19 02:41:46',
    createUser: null,
    createUserAvatar: null,
    createUserName: null,
    updatedAt: '2025-11-21 17:32:26',
    updateUser: '1',
    updateUserAvatar:
      'https://ts1.tc.mm.bing.net/th/id/R-C.6a6d08e2769800fe626bdf3ccbd7b2bf?rik=f2hCf09zz%2f9k3w&riu=http%3a%2f%2fpic.imeitou.com%2fuploads%2fallimg%2f240318%2f10-24031Q62553.jpg&ehk=xiruSwoAcF8DeN%2bzMk5g%2bRv%2baNwdPsxj4YUV4CLEe2A%3d&risl=&pid=ImgRaw&r=0',
    updateUserName: '超级管理员',
    id: '1',
    pid: '0',
    name: 'dashboard',
    path: '/dashboard',
    componentPath: '/dashboard/index.vue',
    redirect: null,
    externalUrl: null,
    menuType: 0,
    openTarget: 0,
    iframeAttrs: null,
    title: '仪表盘',
    icon: 'dashboard',
    sort: 1,
    keepAlive: true,
    visible: true,
    pined: true,
    withoutTab: true,
    parameters: null,
    extraParams: null,
    children: null
  },
  {
    isDeleted: false,
    deletedAt: null,
    deleteUser: null,
    createdAt: '2025-11-19 02:41:46',
    createUser: null,
    createUserAvatar: null,
    createUserName: null,
    updatedAt: '2025-11-19 02:41:46',
    updateUser: null,
    updateUserAvatar: null,
    updateUserName: null,
    id: '10',
    pid: '9',
    name: 'authaccount',
    path: '/auth/account',
    componentPath: '/auth/authaccount/index.vue',
    redirect: null,
    externalUrl: null,
    menuType: 0,
    openTarget: 0,
    iframeAttrs: null,
    title: '账号管理',
    icon: 'user',
    sort: 1,
    keepAlive: true,
    visible: true,
    pined: false,
    withoutTab: false,
    parameters: null,
    extraParams: null,
    children: null
  },
  {
    isDeleted: false,
    deletedAt: null,
    deleteUser: null,
    createdAt: '2025-11-19 02:41:46',
    createUser: null,
    createUserAvatar: null,
    createUserName: null,
    updatedAt: '2025-11-19 02:41:46',
    updateUser: null,
    updateUserAvatar: null,
    updateUserName: null,
    id: '15',
    pid: '14',
    name: 'userprofile',
    path: '/user/profile',
    componentPath: '/user/userprofile/index.vue',
    redirect: null,
    externalUrl: null,
    menuType: 0,
    openTarget: 0,
    iframeAttrs: null,
    title: '用户信息',
    icon: 'user-marked',
    sort: 1,
    keepAlive: true,
    visible: true,
    pined: false,
    withoutTab: false,
    parameters: null,
    extraParams: null,
    children: null
  },
  {
    isDeleted: false,
    deletedAt: null,
    deleteUser: null,
    createdAt: '2025-11-19 02:41:46',
    createUser: null,
    createUserAvatar: null,
    createUserName: null,
    updatedAt: '2025-11-19 02:41:46',
    updateUser: null,
    updateUserAvatar: null,
    updateUserName: null,
    id: '20',
    pid: '19',
    name: 'login',
    path: '/authentication/login',
    componentPath: '/authentication/login.vue',
    redirect: null,
    externalUrl: null,
    menuType: 0,
    openTarget: 0,
    iframeAttrs: null,
    title: '登录',
    icon: 'login',
    sort: 1,
    keepAlive: false,
    visible: true,
    pined: false,
    withoutTab: false,
    parameters: null,
    extraParams: null,
    children: null
  },
  {
    isDeleted: false,
    deletedAt: null,
    deleteUser: null,
    createdAt: '2025-11-19 02:41:46',
    createUser: null,
    createUserAvatar: null,
    createUserName: null,
    updatedAt: '2025-11-19 02:41:46',
    updateUser: null,
    updateUserAvatar: null,
    updateUserName: null,
    id: '25',
    pid: '24',
    name: '404',
    path: '/code/404',
    componentPath: '/code/404.vue',
    redirect: null,
    externalUrl: null,
    menuType: 0,
    openTarget: 0,
    iframeAttrs: null,
    title: '404页面',
    icon: 'file-unknown',
    sort: 1,
    keepAlive: false,
    visible: true,
    pined: false,
    withoutTab: false,
    parameters: null,
    extraParams: null,
    children: null
  },
  {
    isDeleted: false,
    deletedAt: null,
    deleteUser: null,
    createdAt: '2025-11-19 02:41:46',
    createUser: null,
    createUserAvatar: null,
    createUserName: null,
    updatedAt: '2025-11-19 02:41:46',
    updateUser: null,
    updateUserAvatar: null,
    updateUserName: null,
    id: '3',
    pid: '2',
    name: 'sysmenu',
    path: '/system/menu',
    componentPath: '/system/sysmenu/index.vue',
    redirect: null,
    externalUrl: null,
    menuType: 0,
    openTarget: 0,
    iframeAttrs: null,
    title: '菜单管理',
    icon: 'menu',
    sort: 1,
    keepAlive: true,
    visible: true,
    pined: false,
    withoutTab: false,
    parameters: null,
    extraParams: null,
    children: null
  },
  {
    isDeleted: false,
    deletedAt: null,
    deleteUser: null,
    createdAt: '2025-11-19 02:41:46',
    createUser: null,
    createUserAvatar: null,
    createUserName: null,
    updatedAt: '2025-11-19 02:41:46',
    updateUser: null,
    updateUserAvatar: null,
    updateUserName: null,
    id: '7',
    pid: '6',
    name: 'configgroup',
    path: '/config/group',
    componentPath: '/config/configgroup/index.vue',
    redirect: null,
    externalUrl: null,
    menuType: 0,
    openTarget: 0,
    iframeAttrs: null,
    title: '配置分组',
    icon: 'setting',
    sort: 1,
    keepAlive: true,
    visible: true,
    pined: false,
    withoutTab: false,
    parameters: null,
    extraParams: null,
    children: null
  },
  {
    isDeleted: false,
    deletedAt: null,
    deleteUser: null,
    createdAt: '2025-11-19 02:41:46',
    createUser: null,
    createUserAvatar: null,
    createUserName: null,
    updatedAt: '2025-11-19 02:41:46',
    updateUser: null,
    updateUserAvatar: null,
    updateUserName: null,
    id: '11',
    pid: '9',
    name: 'authrole',
    path: '/auth/role',
    componentPath: '/auth/authrole/index.vue',
    redirect: null,
    externalUrl: null,
    menuType: 0,
    openTarget: 0,
    iframeAttrs: null,
    title: '角色管理',
    icon: 'user-checked',
    sort: 2,
    keepAlive: true,
    visible: true,
    pined: false,
    withoutTab: false,
    parameters: null,
    extraParams: null,
    children: null
  },
  {
    isDeleted: false,
    deletedAt: null,
    deleteUser: null,
    createdAt: '2025-11-19 02:41:46',
    createUser: null,
    createUserAvatar: null,
    createUserName: null,
    updatedAt: '2025-11-19 02:41:46',
    updateUser: null,
    updateUserAvatar: null,
    updateUserName: null,
    id: '16',
    pid: '14',
    name: 'userinfo',
    path: '/user/info',
    componentPath: '/user/userinfo/index.vue',
    redirect: null,
    externalUrl: null,
    menuType: 0,
    openTarget: 0,
    iframeAttrs: null,
    title: '账户信息',
    icon: 'info-circle',
    sort: 2,
    keepAlive: true,
    visible: true,
    pined: false,
    withoutTab: false,
    parameters: null,
    extraParams: null,
    children: null
  },
  {
    isDeleted: false,
    deletedAt: null,
    deleteUser: null,
    createdAt: '2025-11-19 02:41:46',
    createUser: null,
    createUserAvatar: null,
    createUserName: null,
    updatedAt: '2025-11-19 02:41:46',
    updateUser: null,
    updateUserAvatar: null,
    updateUserName: null,
    id: '2',
    pid: '0',
    name: 'system',
    path: '/system',
    componentPath: null,
    redirect: null,
    externalUrl: null,
    menuType: 0,
    openTarget: 0,
    iframeAttrs: null,
    title: '系统管理',
    icon: 'setting',
    sort: 2,
    keepAlive: false,
    visible: true,
    pined: false,
    withoutTab: false,
    parameters: null,
    extraParams: null,
    children: null
  },
  {
    isDeleted: false,
    deletedAt: null,
    deleteUser: null,
    createdAt: '2025-11-19 02:41:46',
    createUser: null,
    createUserAvatar: null,
    createUserName: null,
    updatedAt: '2025-11-19 02:41:46',
    updateUser: null,
    updateUserAvatar: null,
    updateUserName: null,
    id: '21',
    pid: '19',
    name: 'register',
    path: '/authentication/register',
    componentPath: '/authentication/register.vue',
    redirect: null,
    externalUrl: null,
    menuType: 0,
    openTarget: 0,
    iframeAttrs: null,
    title: '注册',
    icon: 'user-add',
    sort: 2,
    keepAlive: false,
    visible: true,
    pined: false,
    withoutTab: false,
    parameters: null,
    extraParams: null,
    children: null
  },
  {
    isDeleted: false,
    deletedAt: null,
    deleteUser: null,
    createdAt: '2025-11-19 02:41:46',
    createUser: null,
    createUserAvatar: null,
    createUserName: null,
    updatedAt: '2025-11-19 02:41:46',
    updateUser: null,
    updateUserAvatar: null,
    updateUserName: null,
    id: '4',
    pid: '2',
    name: 'sysdict',
    path: '/system/dict',
    componentPath: '/system/sysdict/index.vue',
    redirect: null,
    externalUrl: null,
    menuType: 0,
    openTarget: 0,
    iframeAttrs: null,
    title: '数据字典',
    icon: 'book',
    sort: 2,
    keepAlive: true,
    visible: true,
    pined: false,
    withoutTab: false,
    parameters: null,
    extraParams: null,
    children: null
  },
  {
    isDeleted: false,
    deletedAt: null,
    deleteUser: null,
    createdAt: '2025-11-19 02:41:46',
    createUser: null,
    createUserAvatar: null,
    createUserName: null,
    updatedAt: '2025-11-19 02:41:46',
    updateUser: null,
    updateUserAvatar: null,
    updateUserName: null,
    id: '8',
    pid: '6',
    name: 'configitem',
    path: '/config/item',
    componentPath: '/config/configitem/index.vue',
    redirect: null,
    externalUrl: null,
    menuType: 0,
    openTarget: 0,
    iframeAttrs: null,
    title: '配置项管理',
    icon: 'setting',
    sort: 2,
    keepAlive: true,
    visible: true,
    pined: false,
    withoutTab: false,
    parameters: null,
    extraParams: null,
    children: null
  },
  {
    isDeleted: false,
    deletedAt: null,
    deleteUser: null,
    createdAt: '2025-11-19 02:41:46',
    createUser: null,
    createUserAvatar: null,
    createUserName: null,
    updatedAt: '2025-11-19 02:41:46',
    updateUser: null,
    updateUserAvatar: null,
    updateUserName: null,
    id: '12',
    pid: '9',
    name: 'authgroup',
    path: '/auth/group',
    componentPath: '/auth/authgroup/index.vue',
    redirect: null,
    externalUrl: null,
    menuType: 0,
    openTarget: 0,
    iframeAttrs: null,
    title: '用户组管理',
    icon: 'usergroup-add',
    sort: 3,
    keepAlive: true,
    visible: true,
    pined: false,
    withoutTab: false,
    parameters: null,
    extraParams: null,
    children: null
  },
  {
    isDeleted: false,
    deletedAt: null,
    deleteUser: null,
    createdAt: '2025-11-19 02:41:46',
    createUser: null,
    createUserAvatar: null,
    createUserName: null,
    updatedAt: '2025-11-19 02:41:46',
    updateUser: null,
    updateUserAvatar: null,
    updateUserName: null,
    id: '17',
    pid: '14',
    name: 'userpreference',
    path: '/user/preference',
    componentPath: '/user/userpreference/index.vue',
    redirect: null,
    externalUrl: null,
    menuType: 0,
    openTarget: 0,
    iframeAttrs: null,
    title: '偏好设置',
    icon: 'setting',
    sort: 3,
    keepAlive: true,
    visible: true,
    pined: false,
    withoutTab: false,
    parameters: null,
    extraParams: null,
    children: null
  },
  {
    isDeleted: false,
    deletedAt: null,
    deleteUser: null,
    createdAt: '2025-11-19 02:41:46',
    createUser: null,
    createUserAvatar: null,
    createUserName: null,
    updatedAt: '2025-11-19 02:41:46',
    updateUser: null,
    updateUserAvatar: null,
    updateUserName: null,
    id: '22',
    pid: '19',
    name: 'forget',
    path: '/authentication/forget',
    componentPath: '/authentication/forget.vue',
    redirect: null,
    externalUrl: null,
    menuType: 0,
    openTarget: 0,
    iframeAttrs: null,
    title: '忘记密码',
    icon: 'user-password',
    sort: 3,
    keepAlive: false,
    visible: true,
    pined: false,
    withoutTab: false,
    parameters: null,
    extraParams: null,
    children: null
  },
  {
    isDeleted: false,
    deletedAt: null,
    deleteUser: null,
    createdAt: '2025-11-19 02:41:46',
    createUser: null,
    createUserAvatar: null,
    createUserName: null,
    updatedAt: '2025-11-19 02:41:46',
    updateUser: null,
    updateUserAvatar: null,
    updateUserName: null,
    id: '5',
    pid: '2',
    name: 'syslog',
    path: '/system/log',
    componentPath: '/system/syslog/index.vue',
    redirect: null,
    externalUrl: null,
    menuType: 0,
    openTarget: 0,
    iframeAttrs: null,
    title: '操作日志',
    icon: 'system-log',
    sort: 3,
    keepAlive: true,
    visible: true,
    pined: false,
    withoutTab: false,
    parameters: null,
    extraParams: null,
    children: null
  },
  {
    isDeleted: false,
    deletedAt: null,
    deleteUser: null,
    createdAt: '2025-11-19 02:41:46',
    createUser: null,
    createUserAvatar: null,
    createUserName: null,
    updatedAt: '2025-11-19 02:41:46',
    updateUser: null,
    updateUserAvatar: null,
    updateUserName: null,
    id: '6',
    pid: '0',
    name: 'config',
    path: '/config',
    componentPath: null,
    redirect: null,
    externalUrl: null,
    menuType: 0,
    openTarget: 0,
    iframeAttrs: null,
    title: '配置管理',
    icon: 'setting',
    sort: 3,
    keepAlive: false,
    visible: true,
    pined: false,
    withoutTab: false,
    parameters: null,
    extraParams: null,
    children: null
  },
  {
    isDeleted: false,
    deletedAt: null,
    deleteUser: null,
    createdAt: '2025-11-19 02:41:46',
    createUser: null,
    createUserAvatar: null,
    createUserName: null,
    updatedAt: '2025-11-19 02:41:46',
    updateUser: null,
    updateUserAvatar: null,
    updateUserName: null,
    id: '13',
    pid: '9',
    name: 'authpasswordreset',
    path: '/auth/password/reset',
    componentPath: '/auth/authpasswordreset/index.vue',
    redirect: null,
    externalUrl: null,
    menuType: 0,
    openTarget: 0,
    iframeAttrs: null,
    title: '密码重置',
    icon: 'user-password',
    sort: 4,
    keepAlive: true,
    visible: true,
    pined: false,
    withoutTab: false,
    parameters: null,
    extraParams: null,
    children: null
  },
  {
    isDeleted: false,
    deletedAt: null,
    deleteUser: null,
    createdAt: '2025-11-19 02:41:46',
    createUser: null,
    createUserAvatar: null,
    createUserName: null,
    updatedAt: '2025-11-19 02:41:46',
    updateUser: null,
    updateUserAvatar: null,
    updateUserName: null,
    id: '18',
    pid: '14',
    name: 'userstats',
    path: '/user/stats',
    componentPath: '/user/userstats/index.vue',
    redirect: null,
    externalUrl: null,
    menuType: 0,
    openTarget: 0,
    iframeAttrs: null,
    title: '数据统计',
    icon: 'chart-bar',
    sort: 4,
    keepAlive: true,
    visible: true,
    pined: false,
    withoutTab: false,
    parameters: null,
    extraParams: null,
    children: null
  },
  {
    isDeleted: false,
    deletedAt: null,
    deleteUser: null,
    createdAt: '2025-11-19 02:41:46',
    createUser: null,
    createUserAvatar: null,
    createUserName: null,
    updatedAt: '2025-11-19 02:41:46',
    updateUser: null,
    updateUserAvatar: null,
    updateUserName: null,
    id: '23',
    pid: '19',
    name: 'reset',
    path: '/authentication/reset',
    componentPath: '/authentication/reset.vue',
    redirect: null,
    externalUrl: null,
    menuType: 0,
    openTarget: 0,
    iframeAttrs: null,
    title: '重置密码',
    icon: 'user-password',
    sort: 4,
    keepAlive: false,
    visible: true,
    pined: false,
    withoutTab: false,
    parameters: null,
    extraParams: null,
    children: null
  },
  {
    isDeleted: false,
    deletedAt: null,
    deleteUser: null,
    createdAt: '2025-11-19 02:41:46',
    createUser: null,
    createUserAvatar: null,
    createUserName: null,
    updatedAt: '2025-11-19 02:41:46',
    updateUser: null,
    updateUserAvatar: null,
    updateUserName: null,
    id: '9',
    pid: '0',
    name: 'auth',
    path: '/auth',
    componentPath: null,
    redirect: null,
    externalUrl: null,
    menuType: 0,
    openTarget: 0,
    iframeAttrs: null,
    title: '权限管理',
    icon: 'user-safety',
    sort: 4,
    keepAlive: false,
    visible: true,
    pined: false,
    withoutTab: false,
    parameters: null,
    extraParams: null,
    children: null
  },
  {
    isDeleted: false,
    deletedAt: null,
    deleteUser: null,
    createdAt: '2025-11-19 02:41:46',
    createUser: null,
    createUserAvatar: null,
    createUserName: null,
    updatedAt: '2025-11-19 02:41:46',
    updateUser: null,
    updateUserAvatar: null,
    updateUserName: null,
    id: '14',
    pid: '0',
    name: 'user',
    path: '/user',
    componentPath: null,
    redirect: null,
    externalUrl: null,
    menuType: 0,
    openTarget: 0,
    iframeAttrs: null,
    title: '用户中心',
    icon: 'user',
    sort: 5,
    keepAlive: false,
    visible: true,
    pined: false,
    withoutTab: false,
    parameters: null,
    extraParams: null,
    children: null
  },
  {
    isDeleted: false,
    deletedAt: null,
    deleteUser: null,
    createdAt: '2025-11-19 02:41:46',
    createUser: null,
    createUserAvatar: null,
    createUserName: null,
    updatedAt: '2025-11-19 02:41:46',
    updateUser: null,
    updateUserAvatar: null,
    updateUserName: null,
    id: '19',
    pid: '0',
    name: 'authentication',
    path: '/authentication',
    componentPath: null,
    redirect: null,
    externalUrl: null,
    menuType: 0,
    openTarget: 0,
    iframeAttrs: null,
    title: '认证相关',
    icon: 'user-locked',
    sort: 6,
    keepAlive: false,
    visible: true,
    pined: false,
    withoutTab: false,
    parameters: null,
    extraParams: null,
    children: null
  },
  {
    isDeleted: false,
    deletedAt: null,
    deleteUser: null,
    createdAt: '2025-11-19 02:41:46',
    createUser: null,
    createUserAvatar: null,
    createUserName: null,
    updatedAt: '2025-11-19 02:41:46',
    updateUser: null,
    updateUserAvatar: null,
    updateUserName: null,
    id: '24',
    pid: '0',
    name: 'code',
    path: '/code',
    componentPath: null,
    redirect: null,
    externalUrl: null,
    menuType: 0,
    openTarget: 0,
    iframeAttrs: null,
    title: '错误页面',
    icon: 'error-circle',
    sort: 7,
    keepAlive: false,
    visible: true,
    pined: false,
    withoutTab: false,
    parameters: null,
    extraParams: null,
    children: null
  }
]
